### PR TITLE
RT-235: Rename repository

### PR DESCRIPTION
**Pull request by NickFitz**
Changing repo name. Surprising how many odd corners needed to be changed for the directory name changes, but I think I got them all :)

### CODE REVIEW

**Review by dev-digital — APPROVED** [review]

**Review by mforner13 — CHANGES_REQUESTED** [review]
A couple more bits worth updating:

- Package name in `package.json` and `package-lock.json`
- The local db being called `defend` in the Makefile
- References to the defend db

**Review by mforner13 — APPROVED** [review]
👍

**Comment by dev-digital** [comment]
Can this PR also address #26 for duplicated directory name ? 

Not sure if Django as any guideline for this ?

image

**Review by mforner13 — APPROVED** [review]
👍

**Review by dev-digital — APPROVED** [review]

**Pull request merged**
